/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Semantic aliases
        'bg-primary':        '#000000',
        'bg-secondary':      '#020617',
        'surface':           '#5F7F76',
        'primary-action':    '#7FA68C',
        'accent':            '#AEB6A8',
        'text-primary':      '#E5E7EB',
        'text-secondary':    '#9CA3AF',
        // Full Stitch palette
        'on-tertiary':                '#46655d',
        'on-secondary-fixed':         '#3a4137',
        'on-tertiary-fixed-variant':  '#4b6b62',
        'background':                 '#000000',
        'secondary-fixed':            '#dde5d6',
        'secondary-container':        '#363e33',
        'primary-fixed-dim':          '#b5dec2',
        'outline-variant':            '#32457c',
        'tertiary-fixed-dim':         '#c7eadf',
        'surface-container-highest':  '#0a2257',
        'inverse-on-surface':         '#4f5469',
        'inverse-primary':            '#426750',
        'on-primary':                 '#234733',
        'surface-container':          '#0a1839',
        'surface-variant':            '#0a2257',
        'primary-dim':                '#9ac2a7',
        'outline':                    '#6073ad',
        'on-tertiary-container':      '#3e5d55',
        'surface-bright':             '#082768',
        'on-primary-fixed':           '#224632',
        'tertiary':                   '#e5fff6',
        'on-error-container':         '#ff9993',
        'primary-container':          '#2a4e39',
        'error-container':            '#7f2927',
        'surface-tint':               '#a8d0b4',
        'surface-container-low':      '#09122b',
        'on-secondary-container':     '#bac2b3',
        'surface-container-high':     '#0b1d48',
        'inverse-surface':            '#faf8ff',
        'on-surface-variant':         '#96a9e6',
        'tertiary-fixed':             '#d5f8ed',
        'secondary-fixed-dim':        '#cfd7c8',
        'secondary-dim':              '#98a093',
        'tertiary-container':         '#d0f3e7',
        'on-secondary-fixed-variant': '#565e52',
        'surface-container-lowest':   '#000000',
        'error-dim':                  '#bb5551',
        'on-secondary':               '#1b2219',
        'surface-base':               '#070d1f',
        'on-error':                   '#490106',
        'primary-fixed':              '#c3eccf',
        'on-tertiary-fixed':          '#2f4e46',
        'on-background':              '#dfe4ff',
        'tertiary-dim':               '#c7eadf',
        'surface-dim':                '#070d1f',
        'secondary':                  '#98a093',
        'on-surface':                 '#dfe4ff',
        'on-primary-container':       '#b1dabe',
        'on-primary-fixed-variant':   '#3f634d',
        'error':                      '#ee7d77',
        'primary':                    '#a8d0b4',
        'badge-bg':                   '#3e5d55',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        sans:     ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
